from diversity.Codes.hussainDiversity import diversidadHussain
from diversity.Codes.XPLXTP import porcentajesXLPXPT
from diversity.Codes.diversityDimention import diversity_per_dimension
from diversity.Codes.gap_rdp_calculation import compute_gap_rdp
from diversity.Codes.populationEntropy import population_entropy