from Classical_Techniques.Codes.boruta import boruta
from Classical_Techniques.Codes.minimal_redundancy_mazimum_relevance import MRMR
from Classical_Techniques.Codes.mutual_information_classification import MIR
from Classical_Techniques.Codes.recursive_feature_elimination import rfe
from Classical_Techniques.Codes.sequential_feature_selection import SFS